# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6.6
  post_build:
    commands:
      - echo "CodeBuild Status (0 == fail, 1 == success) - $CODEBUILD_BUILD_SUCCEEDING"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "AWS Codebuild success on branch ${BRANCH_NAME} on $(TZ=":US/Eastern" date)"
          aws sns publish --phone-number ${PHONE_NUMBER} --message "AWS CodeBuild success. ${EB_NAME}; ${BRANCH_NAME} branch; on $(TZ=":US/Eastern" date)"
        else
          echo "Build/Deploy failure"
        fi
artifacts:
  files:
    - "**/*"
