version: "3.9"
services:
  app:
    image: joelhoelting/who_said_it_v2_api
    build: .
    volumes:
      - ./rails_app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - ./rails_app/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
volumes:
  db:
