version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: joelhoelting/who_said_it_v2_api
    links:
      - db
    volumes:
      - ./rails_app:/app
  db:
    image: postgres
    volumes:
      - ./rails_app/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
  nginx:
    image: nginx
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 8080:80
