version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    depends_on:
      - app
    networks:
      default:
      nginx_default:
        aliases:
          - who_said_it_v2_api
  # certbot:
  #   image: certbot/certbot3
  #   volumes:
  #     - ./certbot.conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
volumes:
  assets:
networks:
  nginx_default:
    external: true