version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      - nginx_default
volumes:
  assets:
networks:
  nginx_default:
    external: true