version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    networks:
      nginx_default:
          aliases:
              - who_said_it_v2_api
  nginx:
    image: nginx
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
    networks:
      nginx_default:
        aliases:
          - proxy-name
    ports:
      ports:
        - 1234:80
volumes:
  assets:
networks:
  nginx_default:
    external: true