version: '3.9'
networks: 
  backend: 
  frontend: 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: joelhoelting/who_said_it_v2_api
    networks: 
      - backend 
      - frontend 
    volumes:
      - ./rails_app:/app
  database:
    image: postgres
    volumes:
      - ./rails_app/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    networks: 
      backend:  
        aliases: 
        - db 
  nginx:
    image: nginx
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
    networks: 
     - frontend 
    ports:
      - 80:80
