version: '3.9'
networks: 
  backend: 
  frontend: 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: joelhoelting/who_said_it_v2_api
    networks: 
      - backend 
      - frontend 
    volumes:
      - ./rails_app:/app
  database:
    image: postgres
    volumes:
      - ./rails_app/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    networks: 
      backend:  
        aliases: 
        - db 
  nginx:
    image: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/certbot
    networks: 
     - frontend 
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/certbot
    networks: 
     - frontend 
    